### ISSUE TITLE
역할 분담

### ISSUE THREAD

**Issue by YChaeeun** [Nexters/Sticky-Android#2]
[Figma](https://www.figma.com/file/bS1WX4kAGEokwiLU8LJlS0/Design?node-id=205%3A3929)

<img width="1141" alt="스크린샷 2021-01-16 오후 6 18 55" src="https://user-images.githubusercontent.com/46909380/104808098-55b7a680-5827-11eb-8661-950fe36567ef.png">

@hyunss
- 스플래시 & 온보딩
- 주소 찾기
- 공유하기

@YChaeeun 
- 메인
- 백그라운드 작업 (ex. gps)

**상황봐서 나누기**
- 마이페이지 & 더보기 - 늦게 끝난 사람
- 외출권 - 빨리 끝난 사람

**Comment by hyunss** [comment]
확인이요 ㅎ
